mconf/bbb-app-rooms

app/views/layouts/application.html.erb, themes/elos/assets/stylesheets/_definitions.scss, themes/elos/assets/stylesheets/theme-application-mobile.scss, themes/elos/views/scheduled_meetings/_form.html.erb, themes/elos/views/shared/_recording_row.html.erb, themes/elos/views/shared/_scheduled_meeting_row.html.erb
Added viewport metatag.
Mobile design adjustments to:
- scheduled meetings
- recordings
- external join form
- new scheduled meeting form
=> ELOSP-431 Elos mobile design

lib/brightspace_helper.rb
The error happened when we tried to update an calendar event
after the user removed it in the Brightspace interface.
We now check for errors and send post a create calendar event
if the update failed.
=> LTI-32 Fix calendar event update error

app/controllers/brightspace_controller.rb, config/initializers/lograge.rb, lib/brightspace_helper.rb
- Added more descritive error messages and exception backtrace to try to better identify errors.
- Treated some known places that could cause exceptions.
- More information is needed to know what is causing the errors.
=> LTI-35 First attempt to fix event exceptions

app/controllers/rooms_controller.rb, config/application.rb, config/routes.rb, lib/bbb_api.rb, themes/elos/config/locales/en.yml, themes/elos/config/locales/pt.yml, themes/elos/helpers/elos_helper.rb, themes/elos/views/shared/_recording_row.html.erb, themes/elos/views/shared/_recordings.html.erb, themes/elos/views/shared/_scheduled_meetings.html.erb
New env var PLAYBACK_URL_AUTHENTICATION to enable playback auth (default: false)
Also: Add empty list messages to recordings and meetings
=> Add recording playback auth via getRecordingToken

config/locales/en.yml, config/locales/pt.yml, themes/elos/views/shared/_recording_row.html.erb
Edited wait message to join conference
Fix to view the list of recordings
=> Fixes release 0.5.x

config/initializers/rails_admin.rb, config/routes.rb
Added configs show rails admin and/or application
Added basic auth
=> LTI-29 - Rails Admin

app/controllers/rooms_controller.rb, app/models/app_launch.rb, config/application.rb, db/migrate/20210714174949_add_index_on_app_launches_expires_at.rb, db/schema.rb
Added default value for launch days to delete
Added method for delete launches expireds and unconnected with meetings
=> LTI-45 - Remove old app launches

app/models/room.rb
Added params meetingID and Wildcard for getRecordings request
=> LTI-78 - Request get recordings with meetingID

.env, app/views/layouts/_gtm_body.html.erb, app/views/layouts/_gtm_head.html.erb, app/views/layouts/application.html.erb, config/application.rb, config/initializers/rails_admin.rb
Added partials with code analytics, gtm_head and gtm_body
Added variable in application.rb
Added a validation in the rails_admin file to show all models in development (**it's not about the task**)
=> LTI-82 - Add Analytics lti

themes/coc/helpers/coc_helper.rb, themes/coc/views/classes/index.html.erb, themes/coc/views/rooms/show.html.erb, themes/coc/views/shared/_room_header.html.erb
Add conditional to show redirect button for classes_list;
Remove unused codes;
Add click in line with name School for collapsible element in classes_list
=> Fixes theme coc

app/helpers/application_helper.rb, db/migrate/20220117125312_add_external_widget_to_consumer_config.rb, db/schema.rb, themes/elos/views/scheduled_meetings/external.html.erb, themes/elos/views/shared/_external_widget.html.erb, themes/elos/views/shared/_scheduled_meetings.html.erb
Ready to add an external widget
=> LTI-103 - Widget support

app/controllers/scheduled_meetings_controller.rb, config/locales/en.yml, config/locales/es.yml, config/locales/pt.yml, lib/bbb_api.rb, themes/coc/views/scheduled_meetings/_form.html.erb, themes/coc/views/scheduled_meetings/external.html.erb, themes/elos/views/scheduled_meetings/_form.html.erb, themes/elos/views/scheduled_meetings/external.html.erb, themes/rnp/views/scheduled_meetings/_form.html.erb, themes/rnp/views/scheduled_meetings/external.html.erb
Before trying to join meeting check if user is able to join.
=> ELOSP-616 - Show message when limit of participants or meetings is reached

.env.development, Dockerfile, app/jobs/remove_old_app_launch_job.rb, config/initializers/resque.rb, config/routes.rb
Add `/resque` to `/rooms` scope and add `MCONF_SERVE_RESQUE_INTERFACE` environment variable to initialize;
Add loop for workers.
=> LTI-116 - Improvements to workers from version 0.9.0

app/controllers/scheduled_meetings_controller.rb
[PRT-1941](https://www.notion.so/mconf/Integrar-os-par-metros-da-sess-o-do-LTI-com-o-APP-cd554f3182ff467b88d9ce988b9a4c21?pvs=4)
=> [PRT-1941] - add session name to mobile direct join

themes/elos/config/locales/en.yml, themes/elos/config/locales/es.yml, themes/elos/config/locales/pt.yml, themes/rnp/config/locales/en.yml, themes/rnp/config/locales/es.yml, themes/rnp/config/locales/pt.yml
[PRT-1946](https://github.com/mconf/elos-portal/pull/838#issue-2139385313)
=> [PRT-1946] - Add missing translations for video playback type

app/controllers/rooms_controller.rb
=> [PRT-2174] Set 'moodle_groups' cache keys to use the default expiration time

app/helpers/icons_helper.rb, themes/elos/config/locales/en.yml, themes/elos/config/locales/es.yml, themes/elos/config/locales/pt.yml, themes/elos/views/shared/_meeting_row.html.erb, themes/rnp/config/locales/en.yml, themes/rnp/config/locales/es.yml, themes/rnp/config/locales/pt.yml, themes/rnp/views/shared/_meeting_row.html.erb
Also signals deleted recordings with a different color and icon
=> [PRT-2162] Hide options for non-published recordings

app/controllers/scheduled_meetings_controller.rb, lib/bbb_api.rb
- Adds the new metadata but keeps the old one so it can be backwards compatible with older Live's versions
=> [PRT-2333] Add `userdata-bbb_feedback_redirect_url` metadata

.env.example, config/application.rb, config/routes.rb, themes/elos/views/shared/_scheduled_meetings.html.erb, themes/rnp/views/shared/_scheduled_meetings.html.erb
add env var `MCONF_DATA_REPORTS_ENABLED` to control the display of Reports button, page and routes
=> [PRT-2407] Add feature flag for Reports

app/controllers/rooms_controller.rb, app/controllers/scheduled_meetings_controller.rb, app/jobs/create_recurring_events_in_moodle_calendar_job.rb, app/jobs/update_recurring_meetings_job.rb, app/models/scheduled_meeting.rb, config/locales/en.yml, config/locales/es.yml, config/locales/pt.yml, lib/moodle.rb
This pull request introduces improvements to how Moodle calendar events are created and managed for scheduled meetings, with a focus on ensuring activity links are correctly included and that group and activity data are handled more robustly. The changes also improve error handling and localization for calendar event descriptions.
**Moodle integration and calendar event enhancements:**
* Added a new `fetch_moodle_cmid` method to `RoomsController` that retrieves and stores the Moodle course module ID (`cmid`) during app launch, ensuring subsequent operations have access to the activity context. (`app/controllers/rooms_controller.rb`, [[1]](diffhunk://#diff-16e9830311185de1ace2bb01b491a8e704f74aaebeeab2a0d21a72cb090f261eR25) [[2]](diffhunk://#diff-16e9830311185de1ace2bb01b491a8e704f74aaebeea …
=> [PRT-2478] Add activity link to Moodle event description
