mconf/bbb-app-rooms

themes/elos/assets/javascripts/theme-application.js

As said in https://flatpickr.js.org/mobile-support/, when it detects the user is on mobile, it tries to use the native datetime selection, which provides a UX that’s familiar to the user. But when the user tried to schedule a session for the same day, it wouldn't work. So, the native datetime inputs are now disabled. 
It was tested on the mobile versions of Chrome, Samsung Web and Safari browsers.

ELOSP-442 Fix for the datetime picker on mobile

---

app/controllers/scheduled_meetings_controller.rb
app/models/scheduled_meeting.rb
config/locales/en.yml
config/locales/pt.yml
db/migrate/20200826174926_add_disable_flags_to_scheduled_meetings.rb
db/schema.rb
themes/elos/config/locales/en.yml
themes/elos/config/locales/pt.yml
themes/elos/views/scheduled_meetings/_form.html.erb
themes/elos/views/shared/_scheduled_meeting_row.html.erb

New configs:
`disable_external_link`: disables the dropdown option to copy external link to copyboard and redirects users to error 404 if they access the meeting's external link.
`disable_private_chat`: config added to create_options. Disables private chats for non-moderators.
`disable_note`: config added to create_options. Non-moderators can only read shared notes.
- locales
- new migration
- modified views and permitted attributes for scheduled meetings
- modified 'external' action to render error 404 when the link is disabled
- Checkboxes in scheduled meeting `_form` partial are separated in 2 columns on tablets and desktop and 1 column on mobile devices.

Add configs to scheduled meetings

---

app/controllers/application_controller.rb
app/controllers/brightspace_controller.rb
app/controllers/scheduled_meetings_controller.rb
app/controllers/sessions_controller.rb
app/models/brightspace_calendar_event.rb
app/models/scheduled_meeting.rb
config/initializers/omniauth.rb
config/locales/en.yml
config/locales/pt.yml
db/migrate/20201028175923_create_brightspace_calendar_events.rb
db/migrate/20201028181808_remove_brightspace_calendar_event_id_from_scheduled_meetings.rb
db/schema.rb
lib/brightspace_helper.rb
scripts/ngrok_start.sh

The model is primarily used to separate the event from the scheduled
meeting, so we can access it even after the destruction of a
scheduled meeting.

Add BrightspaceCalendarEvent model

---

app/controllers/brightspace_controller.rb
app/controllers/rooms_controller.rb
app/models/app_launch.rb
app/models/brightspace_calendar_event.rb
config/locales/en.yml
config/locales/pt.yml
db/migrate/20201124200408_add_link_id_to_brightspace_calendar_events.rb
db/schema.rb
lib/brightspace_helper.rb

- Added link_id to the BrightspaceCalendarEvent model. It's necessary to remove the link later.
- The quicklink is now inserted in the calendar description. The quicklink redirect the user to external_room_scheduled_meeting_path
- Moved some code from BrightspaceController to BrightspaceHelper module and made a lot of changes to improve the flow of the requests to the API.

ELOSP-578 Include link to the class in the calendar description

---

app/controllers/scheduled_meetings_controller.rb

`nil` is an option of the scheduled meeting's `repeat` param. By trying to delete the param when blank in order to make it `nil`, this param wouldn't be passed on the update action. Now, `repeat` is set to `nil` if it is blank.

ELOSP-577 Scheduled meeting's 'repeat' set to nil if blank

---

app/controllers/scheduled_meetings_controller.rb
app/models/scheduled_meeting.rb

Call `update_to_next_recurring_date` on `ScheduledMeeting::external`.

LTI-42 Fix ended recurring meetings

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/models/concerns/friendlyable.rb
app/models/scheduled_meeting.rb
config/initializers/friendly_id.rb
db/migrate/20210504222633_add_hash_id_to_scheduled_meetings.rb
db/schema.rb

A hash_id field was added to store the random id.
The friendly_id gem is used, it's not really necessary but might be
handy in the future.
The Friendlyable concern is responsible for creating a random and unique
hash_id.

LTI-53 Make ScheduledMeeting URL ids random

---

app/helpers/application_helper.rb
app/models/abilities.rb
db/migrate/20210525175309_add_download_presentation_video_to_consumer_config.rb
db/schema.rb
themes/elos/views/shared/_recording_row.html.erb

With this configuration option in the consumer config, you can define whether to allow the download of the recording or not.
By default all users can download, download_presentation_video is true. When not true only users within the defined group of roles have access to the download link

LTI-52 Added permission download recording

---

config/environments/production.rb
config/initializers/assets.rb
themes/elos/assets/stylesheets/_definitions.scss

Enabled ES6 syntax in js_compressor => https://github.com/lautis/uglifier/issues/127
Fixed path to get image in definition.scss file
Added path's to precompile images

Fixed release 0.5.x elos

---

app/models/abilities.rb

The check for `:download_presentation_video` was failing if there was no `ConsumerConfig` in the database for the target room. Added a few checks to make sure there will be a default (all users can download the video) and it will only be changed if there's an specific configuration for it.

LTI-69 Fix on Abilities when there's no ConsumerConfig

---

app/controllers/brightspace_controller.rb
app/models/brightspace_calendar_event.rb
app/models/scheduled_meeting.rb
db/migrate/20210706140832_change_brightspace_calendar_event_foreign_key.rb
db/schema.rb
lib/brightspace_helper.rb

The parameter passed in the URL (send_calendar_update_event, etc.) is a
hash_id due to previous changes.
BrightspaceCalendarEvent was storing the scheduled_meeting_id instead of
the scheduled_meeting_hash_id and the event was never found.
It was necessary to change the event model to store the hash_id because the
schedule_meeting object doens't exist in the DB anymore when the
action is called.

[Cherry pick da LTI-71] Fix error on meeting destruction

---

app/controllers/brightspace_controller.rb
app/models/brightspace_calendar_event.rb
app/models/scheduled_meeting.rb
db/migrate/20210706140832_change_brightspace_calendar_event_foreign_key.rb
db/schema.rb
lib/brightspace_helper.rb

The parameter passed in the URL (send_calendar_update_event, etc.) is a
hash_id due to previous changes.
BrightspaceCalendarEvent was storing the scheduled_meeting_id instead of
the scheduled_meeting_hash_id and the event was never found.
It was necessary to change the event model to store the hash_id because the
schedule_meeting object doens't exist in the DB anymore when the
action is called.

LTI-71 Fix error on meeting destruction

---

Gemfile
Gemfile.lock
lib/bbb_api.rb

This version replaces the `debug` flag with an option to pass the application's logger to the gem,
so they can share the same format and log_level.
Updated the `BigBlueButtonApi` initialization to pass the Rails logger.

LTI-100 Upgrade bigbluebutton-api-ruby gem to 1.8.0 from 1.7.0

---

app/controllers/application_controller.rb
config/locales/es-rails-i18n.yml
config/locales/es.yml
themes/elos/config/locales/es.yml
themes/rnp/config/locales/es.yml

- Added Spanish language locale recognition in `controllers/application_controller.rb`
- Added 3 locale files - `config/locales/es-rails-i18n.yml`, with standard rails i18n translations, `config/locales/es.yml` and `themes/elos/config/locales/es.yml`, with specific translations for the application.

LTI-3 Add spanish language

---

config/routes.rb
themes/coc/views/shared/_scheduled_meeting_row.html.erb
themes/elos/views/shared/_scheduled_meeting_row.html.erb
themes/rnp/views/shared/_scheduled_meeting_row.html.erb

Route `/join` modified from post to get.
When clicking open in new tab, the browser wait for a `get` request, but the route was set as post

LTI-104 - Click fix open conference in new tab

---

scripts/ngrok_start.sh

Couple of modifications on the `start_ngrok.sh` script to run as expected if the ngrok's version is `3.x`:
* The path to the ngrok.log file was changed to the be created on the same path as the ngrok's config file;
* When reading from the log file, the ngrok's URL protocol now can be either HTTP or HTTPS.

LTI-112: `start_ngrok.sh` support for ngrok v3.x

---

app/controllers/rooms_controller.rb
app/models/app_launch.rb
app/models/scheduled_meeting.rb
spec/models/app_launch_spec.rb

Set 'Portal COC' as origin for COC's meetings.
Uses the new `coc_launch?` method to check if the app_launch is from COC portal.

[LTI-105] Add COC origin to meetings

---

lib/bbb_api.rb

- The `mconf_custom_language` metadata was replaced with `bbb_override_default_locale` and now has been removed

ELOSP-867: removes the 'mconf_custom_language' metadata no longer used

---

app/assets/javascripts/meetings.js
app/controllers/rooms_controller.rb
themes/elos/config/locales/en.yml
themes/elos/config/locales/es.yml
themes/elos/config/locales/pt.yml
themes/elos/views/shared/_meeting_data_download.html.erb
themes/elos/views/shared/_meeting_row.html.erb
themes/rnp/config/locales/en.yml
themes/rnp/config/locales/es.yml
themes/rnp/config/locales/pt.yml
themes/rnp/views/shared/_meeting_data_download.html.erb
themes/rnp/views/shared/_meeting_row.html.erb

- Now instead of being loaded with the page, the meeting notes and participants list are loading by clicking on the meeting options dropdown
- When the files fetch returns empty, is displayed messages of unavailable files
- The download items are now of the 'button_to' type and don't generate links, so you can't access them any other way than logged in

LTI-136: Fixes v0.9.0

---

app/assets/javascripts/meetings.js

- Add via js the `target='_blank'` attribute to the learning dashboard button

PRT-1925: fix opening learning dashboard in a new tab

---

themes/elos/config/locales/en.yml
themes/elos/config/locales/es.yml
themes/elos/config/locales/pt.yml
themes/rnp/config/locales/en.yml
themes/rnp/config/locales/es.yml
themes/rnp/config/locales/pt.yml

Rename learning dashboard to engagement report in all languages
**PT:**
Painel de aprendizagem => Relatório de engajamento
Painel de aprendizagem indisponível => Relatório de engajamento indisponível
**EN:**
Learning dashboard => Engagement report
Unavailable learning dashboard => Unavailable engagement report
**ES:**
Panel de aprendizaje => Informe de participación
Panel de aprendizaje no disponible => Informe de participación no disponible

[PRT-1960] Fix: renames engagement report

---

app/controllers/application_controller.rb
app/models/scheduled_meeting.rb

Now a link to a `scheduled_meeting` only works with its `hash_id`.

[PRT-574] Disable redirection of scheduled_meetings links with numeric IDs

---

config/initializers/session_store.rb

Monkeypatch methods that define the cookies header, in both `rack` and `rails` gems

[PRT-2184] Add the `partitioned` attribute to cookies

---

app/controllers/application_controller.rb
app/controllers/scheduled_meetings_controller.rb
app/controllers/sessions_controller.rb
app/views/layouts/application.html.erb
app/views/shared/_toast.html.erb
config/locales/en.yml
config/locales/es.yml
config/locales/pt.yml
config/routes.rb
themes/elos/assets/javascripts/theme-application-elos.js
themes/elos/views/shared/_scheduled_meeting_row.html.erb
themes/elos/views/shared/_scheduled_meetings.html.erb
themes/rnp/assets/javascripts/theme-application-rnp.js
themes/rnp/views/shared/_scheduled_meeting_row.html.erb
themes/rnp/views/shared/_scheduled_meetings.html.erb

A **session token** is a short-lived nonce associated with a specific user session, which can be used to retrieve that session when the application is opened in a external context, such as a new tab, where the original cookie can no longer be accessed.
Changes:
- Route and action to create a session token. A key-pair is stored in the cache (with 2 minutes expiration), associating the session token, a 16-long SecureRandom hex string, to the current `app_launch`. Returns a JSON with the token
- `before_action` to check for and validate a session token, and restore the associated session
- Javascript code to obtain a session token and append it to links that open in a new tab. The link must have the class `create-session-token`
- Retrieve the session on `scheduled_meetings#join` action

[PRT-2185] Session tokens

---

app/assets/javascripts/meetings.js
app/controllers/application_controller.rb
app/controllers/meetings_controller.rb
app/helpers/meetings_helper.rb
themes/elos/assets/javascripts/theme-application-elos.js
themes/elos/views/errors/index.html.erb
themes/rnp/assets/javascripts/theme-application-rnp.js
themes/rnp/views/errors/index.html.erb

The meeting data links open in a new tab, so a session token is needed to restore the session and authorize the user in that new tab.

[PRT-2183] Fix meeting data access on new tab

---

app/assets/javascripts/rooms.js
themes/rnp/views/scheduled_meetings/external.html.erb
themes/rnp/views/scheduled_meetings/wait.html.erb
themes/rnp/views/shared/_app_offcanvas.html.erb
themes/rnp/views/shared/_scheduled_meeting_row.html.erb

- If there was more than one `scheduled_meeting` in the `rooms#show` list, clicking the join button of any meeting after the first would open the wrong offcanvas, because they all had the same id (`offcanvasBottom`)
- Now we use the meeting's `hash_id` to identify each offcanvas
- Only affects the RNP theme

[PRT-2290] Fix for app_offcanvas opening the wrong meeting 

---

lib/bbb_api.rb

Now only `bbb_feedback_redirect_url` is used

[PRT-2356] Remove deprecated `mconf_custom_logout_url` join meeting userdata
